# Generated by Django 4.0 on 2022-10-15 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paystack', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('out_of_stock', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('slashed_price', models.IntegerField()),
                ('actual_price', models.IntegerField()),
                ('slash_percentage', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='authentication.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.shop')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_first_name', models.CharField(default='', max_length=255)),
                ('buyer_last_name', models.CharField(default='', max_length=255)),
                ('buyer_email', models.EmailField(default='', max_length=255)),
                ('buyer_phone', models.CharField(blank=True, max_length=15)),
                ('buyer_shipping_address', models.TextField(default='nil')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paystack', models.TextField(default='')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('product_name', models.CharField(max_length=1000)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('iffiliate_earning', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shop_earning', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('order_processing', 'order_processing'), ('ready_to_dispatch', 'ready_to_dispatch'), ('order_dispatched', 'order_dispatched'), ('delivered', 'delivered')], default='order_processing', max_length=50)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.shop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.user')),
            ],
        ),
    ]
