# Generated by Django 4.1.1 on 2022-09-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_amont',
            new_name='total_amount',
        ),
    ]
