# Generated by Django 4.0 on 2022-12-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_orderhistory_image_four_orderhistory_image_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='shopPhone_number',
            field=models.CharField(default='081', max_length=14),
        ),
    ]
