# Generated by Django 4.0 on 2022-12-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_orderhistory_shopphone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
