# Generated by Django 4.1.1 on 2022-10-10 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_orderhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='buyer_email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='buyer_first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='buyer_last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='buyer_shipping_address',
            field=models.TextField(default='nil'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('order_processing', 'order_processing'), ('ready_to_dispatch', 'ready_to_dispatch'), ('order_dispatched', 'order_dispatched'), ('delivered', 'delivered')], default='order_processing', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
