# Generated by Django 4.1.1 on 2022-10-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_orderitem_status_orderhistory_buyer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='iffiliate_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='shop_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
