# Generated by Django 4.0 on 2022-11-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banks',
        ),
    ]
