# Generated by Django 4.0 on 2022-11-14 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_remove_shop_paystack_recipient'),
        ('payment', '0002_delete_banks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopWithdrawHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_code', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transfer_state', models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('reversed', 'reversed'), ('pending', 'pending')], default='pending', max_length=15)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.shop')),
            ],
        ),
    ]
