# Generated by Django 4.0 on 2022-11-14 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_shop_paystack_recipient'),
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopwithdrawhistory',
            name='shop',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.shop'),
        ),
    ]
