# Generated by Django 4.0 on 2022-11-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_shopwithdrawhistory_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopwithdrawhistory',
            name='reference',
            field=models.TextField(default=''),
        ),
    ]
