# Generated by Django 4.0 on 2022-11-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_shopwithdrawhistory_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopwithdrawhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
