# Generated by Django 4.1.1 on 2022-09-07 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('whatsapp', models.URLField()),
                ('instagram', models.URLField()),
                ('about', models.TextField()),
                ('banner', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('logo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('info', models.TextField()),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.IntegerField()),
                ('account_holder_email', models.EmailField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('address_country', models.CharField(max_length=255)),
                ('address_city', models.CharField(max_length=255)),
                ('address_zip', models.IntegerField()),
                ('street_address', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
