# Generated by Django 4.0 on 2022-10-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='paystack_recipient',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
