# Generated by Django 4.0 on 2022-11-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_shop_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='facebook',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='instagram',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='twitter',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='whatsapp',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
