# Generated by Django 4.1.1 on 2022-09-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_shop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address_zip',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='whatsapp',
            field=models.URLField(blank=True),
        ),
    ]
