# Generated by Django 4.0 on 2022-11-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_shop_paystack_recipient'),
        ('authentication', '0003_alter_shop_facebook_alter_shop_instagram_and_more'),
    ]

    operations = [
    ]
