# Generated by Django 4.0 on 2022-11-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_merge_20221114_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='paystack_recipient',
        ),
    ]
