# Generated by Django 4.1.1 on 2022-09-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_shop_created_at_shop_updated_at_user_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='account_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address_zip',
            field=models.CharField(max_length=255),
        ),
    ]
